// DO NOT EDIT THIS FILE! Required to run the assignment.
int main() {
    std::vector<std::string> applicants = get_applicants("students.txt");
    std::vector<const std::string> matches = find_matches(kYourName /* figure this out later */, applicants);
    std::string match = get_match(matches);
    std::cout << "Your match is: " << match << std::endl;
}
