// DO NOT EDIT THIS FILE! Required to run the assignment.
int main(int argc, char* argv[]) {
    bool arg_ok=false;
    std::string student_name;
    if(argc > 1){
        student_name=std::string(argv[1]);
        if(student_name.length() > 0){
            arg_ok=true;
        }
    }
    if(!arg_ok){
        std::cout << "Usage: " << argv[0] << " <your name>" << std::endl;
        return 1;
    }
    std::vector<std::string> applicants = get_applicants("students.txt");
    std::vector<std::string> matches = find_matches(student_name, applicants);
    std::string match = get_match(matches);
    std::cout << "Your match is: " << match << std::endl;
    return 0;
}
